In [1]:
import pandas as  pd

stock_price = pd.read_csv("nestle.csv")

In [2]:
stock_price

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,21-April-2022,18150.00,18572.95,17772.90,18205.80,18130.183442,4590,1770,83217542.0,950.0,20.70,800.05,55.80
1,20-April-2022,18100.10,18415.00,18017.15,18313.70,18295.559071,6069,1321,111035748.0,4677.0,77.06,397.85,213.60
2,19-April-2022,18470.05,18718.00,17845.60,17943.15,18355.093320,2904,716,53303191.0,1619.0,55.75,872.40,-526.90
3,18-April-2022,18294.50,18684.50,18294.50,18549.85,18511.224599,1496,586,27692792.0,557.0,37.23,390.00,255.35
4,13-April-2022,18371.20,18549.30,18248.25,18343.90,18388.967826,1150,550,21147313.0,573.0,49.83,301.05,-27.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548,6-January-2012,4114.00,4160.00,4076.00,4143.25,4129.486321,3107,444,12830314.0,2069.0,66.59,84.00,29.25
2549,5-January-2012,4118.00,4126.90,4080.00,4101.85,4106.848723,1018,270,4180772.0,357.0,35.07,46.90,-16.15
2550,4-January-2012,4100.00,4125.00,4081.40,4120.60,4105.106055,2857,247,11728288.0,2312.0,80.92,43.60,20.60
2551,3-January-2012,4061.00,4110.10,4060.10,4095.35,4091.474315,5003,886,20469646.0,2817.0,56.31,50.00,34.35
2552,2-January-2012,4139.90,4139.90,4044.00,4070.35,4085.640979,7760,1132,31704574.0,5776.0,74.43,95.90,-69.55

In [3]:
stock_price.dtypes

Date                          object
Open Price                   float64
High Price                   float64
Low Price                    float64
Close Price                  float64
WAP                          float64
No.of Shares                   int64
No. of Trades                  int64
Total Turnover (Rs.)         float64
Deliverable Quantity         float64
% Deli. Qty to Traded Qty    float64
Spread High-Low              float64
Spread Close-Open            float64
dtype: object

In [4]:
#data transformation
stock_price.isnull().sum

<bound method DataFrame.sum of        Date  Open Price  High Price  Low Price  Close Price    WAP  \
0     False       False       False      False        False  False
1     False       False       False      False        False  False
2     False       False       False      False        False  False
3     False       False       False      False        False  False
4     False       False       False      False        False  False
...     ...         ...         ...        ...          ...    ...
2548  False       False       False      False        False  False
2549  False       False       False      False        False  False
2550  False       False       False      False        False  False
2551  False       False       False      False        False  False
2552  False       False       False      False        False  False

      No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
0            False          False                 False                 False
1            False          False                 False                 False
2            False          False                 False                 False
3            False          False                 False                 False
4            False          False                 False                 False
...            ...            ...                   ...                   ...
2548         False          False                 False                 False
2549         False          False                 False                 False
2550         False          False                 False                 False
2551         False          False                 False                 False
2552         False          False                 False                 False

      % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open
0                         False            False              False
1                         False            False              False
2                         False            False              False
3                         False            False              False
4                         False            False              False
...                         ...              ...                ...
2548                      False            False              False
2549                      False            False              False
2550                      False            False              False
2551                      False            False              False
2552                      False            False              False

[2553 rows x 13 columns]>

In [5]:
stock_price.isna().sum()

Date                         0
Open Price                   0
High Price                   0
Low Price                    0
Close Price                  0
WAP                          0
No.of Shares                 0
No. of Trades                0
Total Turnover (Rs.)         0
Deliverable Quantity         2
% Deli. Qty to Traded Qty    2
Spread High-Low              0
Spread Close-Open            0
dtype: int64

In [6]:
stock_price = stock_price.fillna(0)

In [7]:
#converting a column to date
stock_price["Date"] = pd.to_datetime(stock_price["Date"])

In [8]:
stock_price

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,2022-04-21,18150.00,18572.95,17772.90,18205.80,18130.183442,4590,1770,83217542.0,950.0,20.70,800.05,55.80
1,2022-04-20,18100.10,18415.00,18017.15,18313.70,18295.559071,6069,1321,111035748.0,4677.0,77.06,397.85,213.60
2,2022-04-19,18470.05,18718.00,17845.60,17943.15,18355.093320,2904,716,53303191.0,1619.0,55.75,872.40,-526.90
3,2022-04-18,18294.50,18684.50,18294.50,18549.85,18511.224599,1496,586,27692792.0,557.0,37.23,390.00,255.35
4,2022-04-13,18371.20,18549.30,18248.25,18343.90,18388.967826,1150,550,21147313.0,573.0,49.83,301.05,-27.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548,2012-01-06,4114.00,4160.00,4076.00,4143.25,4129.486321,3107,444,12830314.0,2069.0,66.59,84.00,29.25
2549,2012-01-05,4118.00,4126.90,4080.00,4101.85,4106.848723,1018,270,4180772.0,357.0,35.07,46.90,-16.15
2550,2012-01-04,4100.00,4125.00,4081.40,4120.60,4105.106055,2857,247,11728288.0,2312.0,80.92,43.60,20.60
2551,2012-01-03,4061.00,4110.10,4060.10,4095.35,4091.474315,5003,886,20469646.0,2817.0,56.31,50.00,34.35
2552,2012-01-02,4139.90,4139.90,4044.00,4070.35,4085.640979,7760,1132,31704574.0,5776.0,74.43,95.90,-69.55

In [9]:
#extracting the year "Y" from the entire date
stock_price["Date"].dt.to_period("Y")

0       2022
1       2022
2       2022
3       2022
4       2022
        ...
2548    2012
2549    2012
2550    2012
2551    2012
2552    2012
Name: Date, Length: 2553, dtype: period[A-DEC]

In [10]:
stock_price["Date"].astype(str).str.split("-")[1]

['2022', '04', '20']

In [11]:
stock_price["Date"].astype(str).str.split("-",expand=True)

         0   1   2
0     2022  04  21
1     2022  04  20
2     2022  04  19
3     2022  04  18
4     2022  04  13
...    ...  ..  ..
2548  2012  01  06
2549  2012  01  05
2550  2012  01  04
2551  2012  01  03
2552  2012  01  02

[2553 rows x 3 columns]

In [12]:
a = stock_price["Date"].astype(str).str.split("-",expand=True)[0]

In [13]:
stock_price.insert(1, "Year", stock_price["Date"].dt.to_period("Y"))

In [14]:
stock_price

,Date,Year,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,2022-04-21,2022,18150.00,18572.95,17772.90,18205.80,18130.183442,4590,1770,83217542.0,950.0,20.70,800.05,55.80
1,2022-04-20,2022,18100.10,18415.00,18017.15,18313.70,18295.559071,6069,1321,111035748.0,4677.0,77.06,397.85,213.60
2,2022-04-19,2022,18470.05,18718.00,17845.60,17943.15,18355.093320,2904,716,53303191.0,1619.0,55.75,872.40,-526.90
3,2022-04-18,2022,18294.50,18684.50,18294.50,18549.85,18511.224599,1496,586,27692792.0,557.0,37.23,390.00,255.35
4,2022-04-13,2022,18371.20,18549.30,18248.25,18343.90,18388.967826,1150,550,21147313.0,573.0,49.83,301.05,-27.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548,2012-01-06,2012,4114.00,4160.00,4076.00,4143.25,4129.486321,3107,444,12830314.0,2069.0,66.59,84.00,29.25
2549,2012-01-05,2012,4118.00,4126.90,4080.00,4101.85,4106.848723,1018,270,4180772.0,357.0,35.07,46.90,-16.15
2550,2012-01-04,2012,4100.00,4125.00,4081.40,4120.60,4105.106055,2857,247,11728288.0,2312.0,80.92,43.60,20.60
2551,2012-01-03,2012,4061.00,4110.10,4060.10,4095.35,4091.474315,5003,886,20469646.0,2817.0,56.31,50.00,34.35
2552,2012-01-02,2012,4139.90,4139.90,4044.00,4070.35,4085.640979,7760,1132,31704574.0,5776.0,74.43,95.90,-69.55

In [15]:
stock_price.dtypes

Date                         datetime64[ns]
Year                          period[A-DEC]
Open Price                          float64
High Price                          float64
Low Price                           float64
Close Price                         float64
WAP                                 float64
No.of Shares                          int64
No. of Trades                         int64
Total Turnover (Rs.)                float64
Deliverable Quantity                float64
% Deli. Qty to Traded Qty           float64
Spread High-Low                     float64
Spread Close-Open                   float64
dtype: object

In [16]:
stock_price["Year"] = stock_price["Year"].astype(str).astype(int)

In [17]:
stock_price.dtypes

Date                         datetime64[ns]
Year                                  int32
Open Price                          float64
High Price                          float64
Low Price                           float64
Close Price                         float64
WAP                                 float64
No.of Shares                          int64
No. of Trades                         int64
Total Turnover (Rs.)                float64
Deliverable Quantity                float64
% Deli. Qty to Traded Qty           float64
Spread High-Low                     float64
Spread Close-Open                   float64
dtype: object

In [18]:
#Building the ML model
#step 1:
#Identify the independent(features) and dependent(target) columns

x = stock_price.drop(["Date", "Close Price"], axis=1)
y = stock_price["Close Price"]

In [19]:
x

,Year,Open Price,High Price,Low Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open
0,2022,18150.00,18572.95,17772.90,18130.183442,4590,1770,83217542.0,950.0,20.70,800.05,55.80
1,2022,18100.10,18415.00,18017.15,18295.559071,6069,1321,111035748.0,4677.0,77.06,397.85,213.60
2,2022,18470.05,18718.00,17845.60,18355.093320,2904,716,53303191.0,1619.0,55.75,872.40,-526.90
3,2022,18294.50,18684.50,18294.50,18511.224599,1496,586,27692792.0,557.0,37.23,390.00,255.35
4,2022,18371.20,18549.30,18248.25,18388.967826,1150,550,21147313.0,573.0,49.83,301.05,-27.30
...,...,...,...,...,...,...,...,...,...,...,...,...
2548,2012,4114.00,4160.00,4076.00,4129.486321,3107,444,12830314.0,2069.0,66.59,84.00,29.25
2549,2012,4118.00,4126.90,4080.00,4106.848723,1018,270,4180772.0,357.0,35.07,46.90,-16.15
2550,2012,4100.00,4125.00,4081.40,4105.106055,2857,247,11728288.0,2312.0,80.92,43.60,20.60
2551,2012,4061.00,4110.10,4060.10,4091.474315,5003,886,20469646.0,2817.0,56.31,50.00,34.35
2552,2012,4139.90,4139.90,4044.00,4085.640979,7760,1132,31704574.0,5776.0,74.43,95.90,-69.55

In [20]:
y

0       18205.80
1       18313.70
2       17943.15
3       18549.85
4       18343.90
          ...
2548     4143.25
2549     4101.85
2550     4120.60
2551     4095.35
2552     4070.35
Name: Close Price, Length: 2553, dtype: float64

In [21]:
#step 2:
#split x and y
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.6, random_state=0)

In [22]:
#step 3:
#call the algorithm

from sklearn.linear_model import LinearRegression
model =  LinearRegression()

In [23]:
#step 4:
#train the model 
model = model.fit(x_train, y_train)

In [24]:
#step 5:
#make predictions on the x_test values

prediction = model.predict(x_test)

In [25]:
prediction.round(0)

array([15544., 15363., 11872., ..., 11697.,  7141.,  5059.])

In [26]:
#step 6:
#check the accuracy
from sklearn.metrics import r2_score
r2_score(y_test, prediction)*100

100.0

In [27]:
#the model is perfect

In [28]:
#predict the close price of Nestle stock price if:
#Year - 2022
#Open price - 12000
#High price - 13000
#Low price - 15000
#WAP - 12000
#No. of Shares - 5000
#No. of Trades - 1000
#Total Turnover - 50245120
#Deliverable Quantity - 900
#% Deli. Qty to Traded Qty - 50.20
#Spread High Low - 900
#Spread Close-Open - 200

In [29]:
model.predict([[2022, 12000, 13000, 15000, 12000, 5000, 1000, 50245120, 900, 50.20, 900, 200]]).round()

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12200.])